// Define an operation
export interface Operacion {
  _id: string;
  fecInicio: string;
  fecFinal: string;
  estadoOperacion: boolean;
  currentStage: string,
  nextStage: string
  procesos: Proceso[]; // Changed to use Proceso interface
}

// Define a new operation (without _id as it will be generated by the server)
export interface NewOperacion extends Omit<Operacion, '_id'> {
  _id?: string;
}

// Define a process
// Update the Proceso interface to use ProcesoDetail
export interface Proceso {
  _id?: string;
  tipo: string;
  fecha: any;
  hora: any;
  operacionId?: string;
  responsable: Responsable; // Mantener como objeto en el frontend
  detalles: ProcesoDetail[]; // Changed to use ProcesoDetail interface
  estado: boolean;
  createdAt: string;
  nextStage?: string;
}

// Define el tipo Responsable como un objeto
export interface Responsable {
  _id?: string;
  nombreCompleto?: string | null;
  puesto?: string;
  area?: string;
}

// Añadir tipo para nuevo proceso
export interface NewProceso extends Omit<Proceso, '_id' | 'createdAt' | 'responsable'> {
  _id?: string;
  createdAt?: string;
  responsable: { _id: string }; // Enviar solo el _id del responsable en las solicitudes HTTP
}

// Define the detail of a process
export interface ProcesoDetail {
  numOrden: string;
  maquina:  Maquina; 
  cantPrendas: number;
  etiqueta?: string;
  observaciones?: string;
}

// Define el tipo Maquina como un objeto
export interface Maquina {
  _id: string;
  nombreMaquina?: string;
  tipo?: string;
  modelo?: string;
  marca?: string;
}
// Define filters for fetching operations
export interface OperacionFilters {
  estadoOperacion?: boolean;
  page?: number;
  limit?: number;
}

// Define the response from the API
export interface ApiResponse<T> {
  success: boolean;
  message?: string;
  data: T;
}

// Define the response for fetching processes
export interface ProcesoResponse {
  procesos: Proceso[];
  total: number;
}

// Define the response for fetching operations
export interface OperacionResponse {
  operaciones: Operacion[];
  total: number;
}

// Define the response for a single operation
export interface SingleOperacionResponse {
  operacion: Operacion;
}

// Define the response for a single process
export interface SingleProcesoResponse {
  proceso: Proceso;
}

// Define the filters for fetching processes
export interface ProcesoFilters {
  numOrden?: string;
  tipo?: string;
  fecha?: string;
  responsable?: string;
  estado?: boolean;
  page?: number; // Added page property
  limit?: number; // Added limit property
  operacionId?: string; // Added operacionId property
  sucursalId?: string; // Added sucursalId property
  maquinaId?: string; // Added maquinaId property
}

// Define the filters for fetching operations by order number
export interface ProcesoByNumOrdenFilters {
  numOrden: string;
}

